# Generated by Django 3.2.11 on 2022-01-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_car_car_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_registration_number',
            field=models.CharField(default='XX 1234', max_length=10),
        ),
    ]
