# Generated by Django 3.2.11 on 2022-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_alter_car_car_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
