# Generated by Django 3.2.11 on 2022-01-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_auto_20220115_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rent_end_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rent_start_date',
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_date', models.DateField(blank=True, null=True)),
                ('rent_end_date', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.car')),
            ],
        ),
    ]
