# Generated by Django 3.2.11 on 2022-01-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_auto_20220117_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='car',
            new_name='rented_car',
        ),
    ]
