# Generated by Django 2.2.4 on 2022-02-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0010_auto_20220201_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_fuel',
            field=models.CharField(choices=[('GAS', 'Benzyna'), ('LPG', 'LPG'), ('ELE', 'Elektryczny')], default='GAS', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='car_price_per_day',
            field=models.DecimalField(decimal_places=2, default=150.01, max_digits=6),
        ),
        migrations.AddField(
            model_name='car',
            name='car_transmission',
            field=models.CharField(choices=[('AUT', 'Automatyczna'), ('MAN', 'Manualna')], default='MAN', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='car_year',
            field=models.PositiveIntegerField(default=2010),
        ),
    ]
