# Generated by Django 2.2.4 on 2022-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0011_auto_20220227_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car_fuel',
            field=models.CharField(choices=[('GAS', 'Benzyna'), ('LPG', 'LPG'), ('ELE', 'Elektryczny')], default='GAS', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_transmission',
            field=models.CharField(choices=[('AUT', 'Automatyczna'), ('MAN', 'Manualna')], default='MAN', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_year',
            field=models.PositiveIntegerField(default=2010),
        ),
    ]
