# Generated by Django 2.2.4 on 2022-02-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0013_auto_20220227_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
