# Generated by Django 2.2.4 on 2022-02-27 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_delete_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_seats',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
