# Generated by Django 2.2.4 on 2022-03-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0015_auto_20220227_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_fuel',
            field=models.CharField(choices=[('GAS', 'Benzyna'), ('DIE', 'Diesel'), ('LPG', 'LPG'), ('ELE', 'Elektryczny'), ('HYB', 'Hybryda')], default='GAS', max_length=10),
        ),
    ]
