# Generated by Django 2.2.4 on 2022-03-02 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0016_auto_20220302_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_seats',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
